# Generated by Django 5.0.4 on 2024-04-04 10:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_awards_genres_titles'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Awards',
            new_name='Award',
        ),
        migrations.RenameModel(
            old_name='Genres',
            new_name='Genre',
        ),
        migrations.RenameModel(
            old_name='Titles',
            new_name='Title',
        ),
        migrations.RenameField(
            model_name='title',
            old_name='awards',
            new_name='award',
        ),
    ]
