# Generated by Django 5.0.4 on 2024-04-04 12:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0005_budget_name_rating'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='budget',
            name='movie',
        ),
        migrations.RemoveField(
            model_name='rating',
            name='movie_title',
        ),
    ]
