# Generated by Django 5.0.4 on 2024-04-04 12:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0006_remove_budget_movie_remove_rating_movie_title'),
    ]

    operations = [
        migrations.AddField(
            model_name='budget',
            name='movie',
            field=models.CharField(default=0, max_length=100, verbose_name=models.ManyToManyField(to='title')),
            preserve_default=False,
        ),
    ]
