# Generated by Django 5.0.4 on 2024-04-04 12:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0007_budget_movie'),
    ]

    operations = [
        migrations.AddField(
            model_name='rating',
            name='movie_title',
            field=models.ManyToManyField(to='app.title'),
        ),
        migrations.RemoveField(
            model_name='budget',
            name='movie',
        ),
        migrations.AddField(
            model_name='budget',
            name='movie',
            field=models.ManyToManyField(to='app.title'),
        ),
    ]
